Move clean processes to an earlier stage.

diff --git a/mingw-w64-build b/mingw-w64-build
--- a/mingw-w64-build
+++ b/mingw-w64-build
@@ -438,29 +438,6 @@ default install-dir: ${HOME}/toolchains/mingw-w64-${MINGW_W64_VER}-gcc-${GCC_VER
     PKG_DIR="${TARGET_DIR}/pkg"
     SOURCE_DIR="${TARGET_DIR}/source"
     BUILD_DIR="${TARGET_DIR}/build-${PREFIX}"
-    if [[ -e "${MINGW_W64_DIR}" ]]; then
-        if [[ "${FORCE}" == true ]]; then
-            rm -rf "${MINGW_W64_DIR}"
-        else
-            # prefix dir should not exist
-            echo "unable to create directory (exists): ${MINGW_W64_DIR}" >&2
-            echo "remove with: ${SELF_NAME} ${TARGET_PARAM%%.*}.distclean${2:+ $2}" >&2
-            return 1
-        fi
-    fi
-    if [[ -e "${SOURCE_DIR}" ]]; then
-        # never reuse source dir
-        rm -rf "${SOURCE_DIR}"
-    fi
-    if [[ -e "${BUILD_DIR}" ]]; then
-        # never reuse build dir
-        rm -rf "${BUILD_DIR}"
-    fi
-    mkdir -p "${TARGET_DIR}"
-    if [[ ! -d "${TARGET_DIR}" ]]; then
-        echo "unable to create directory: ${TARGET_DIR}" >&2
-        return 1
-    fi
 
     # clean
     case "${TARGET_PARAM}" in
@@ -482,6 +459,33 @@ default install-dir: ${HOME}/toolchains/mingw-w64-${MINGW_W64_VER}-gcc-${GCC_VER
             return 0
             ;;
     esac
+
+    # remove non-reusable directories
+    if [[ -e "${MINGW_W64_DIR}" ]]; then
+        if [[ "${FORCE}" == true ]]; then
+            rm -rf "${MINGW_W64_DIR}"
+        else
+            # prefix dir should not exist
+            echo "unable to create directory (exists): ${MINGW_W64_DIR}" >&2
+            echo "remove with: ${SELF_NAME} ${TARGET_PARAM%%.*}.distclean${2:+ $2}" >&2
+            return 1
+        fi
+    fi
+    if [[ -e "${SOURCE_DIR}" ]]; then
+        # never reuse source dir
+        rm -rf "${SOURCE_DIR}"
+    fi
+    if [[ -e "${BUILD_DIR}" ]]; then
+        # never reuse build dir
+        rm -rf "${BUILD_DIR}"
+    fi
+
+    # create target directory
+    mkdir -p "${TARGET_DIR}"
+    if [[ ! -d "${TARGET_DIR}" ]]; then
+        echo "unable to create directory: ${TARGET_DIR}" >&2
+        return 1
+    fi
 
     # verify/fetch
     mkdir -p "${PKG_DIR}"
